### ISSUE TITLE
Uncaught Exception Type: mysqli_sql_exception 

### ISSUE THREAD

**Issue by catalyst234** [alextselegidis/easyappointments-docker#11]
Starting the container on my Synology NAS, I received the following error message:

> An uncaught Exception was encountered
> 
> Type
> mysqli_sql_exception
> 
> Message
> Connection refused
> 
> Filename
> /var/www/html/system/database/drivers/mysqli/mysqli_driver.php
> 
> Line Number
> 203

Google was no help. What should I do?

**Comment by jgarner9** [comment]
What parameters did you provide for your DB? This seems to be the connection is refusing to your DB, so possibly the creds for the DB or the host is incorrect. One common recommendation I saw was trying to replace localhost as the host for 127.0.0.1 if this is locally hosted: https://matomo.org/faq/troubleshooting/how-do-i-fix-the-mysql-error-connection-refused/

**Comment by alextselegidis** [comment]
It seems that this was a configuration error that it is now resolved.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
